//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auction
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bid
    {
        public int ID { get; set; }
        public int AuctionID { get; set; }
        public int ClientID { get; set; }
        public decimal Amount { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<bool> IsAuto { get; set; }
    
        public virtual Auction Auction { get; set; }
        public virtual Client Client { get; set; }
    }
}
